DELETE FROM table_stockparts;

INSERT INTO table_stockparts(stockparts_name, stockparts_sizemodel, stockparts_unitprice, stockparts_nocolorstock) VALUES('stand', 1, 30, 1000);
INSERT INTO table_stockparts(stockparts_name, stockparts_sizemodel, stockparts_unitprice, stockparts_nocolorstock) VALUES('brake kit', 1, 45, 1000);
INSERT INTO table_stockparts(stockparts_name, stockparts_sizemodel, stockparts_unitprice, stockparts_nocolorstock) VALUES('gear kit', 1, 60, 1000);
INSERT INTO table_stockparts(stockparts_name, stockparts_sizemodel, stockparts_unitprice, stockparts_whitestock, stockparts_blackstock, stockparts_purplestock) VALUES ('frame', 1, 120, 100, 150, 200);
INSERT INTO table_stockparts(stockparts_name, stockparts_sizemodel, stockparts_unitprice, stockparts_whitestock, stockparts_blackstock, stockparts_purplestock) VALUES ('frame', 2, 130, 200, 140, 800);
INSERT INTO table_stockparts(stockparts_name, stockparts_sizemodel, stockparts_unitprice, stockparts_whitestock, stockparts_blackstock, stockparts_purplestock) VALUES ('reinforced frame', 1, 180, 230, 120, 400);
INSERT INTO table_stockparts(stockparts_name, stockparts_sizemodel, stockparts_unitprice, stockparts_whitestock, stockparts_blackstock, stockparts_purplestock) VALUES ('reinforced frame', 2, 200, 100, 100, 80);
INSERT INTO table_stockparts(stockparts_name, stockparts_sizemodel, stockparts_unitprice, stockparts_nocolorstock) VALUES('crankset kit', 1, 40, 300);
INSERT INTO table_stockparts(stockparts_name, stockparts_sizemodel, stockparts_unitprice, stockparts_nocolorstock) VALUES('sprocket cassette', 1, 50, 300);
INSERT INTO table_stockparts(stockparts_name, stockparts_sizemodel, stockparts_unitprice, stockparts_nocolorstock) VALUES('reflector', 1, 8, 300);
INSERT INTO table_stockparts(stockparts_name, stockparts_sizemodel, stockparts_unitprice, stockparts_nocolorstock) VALUES('chain', 1, 15, 300);
INSERT INTO table_stockparts(stockparts_name, stockparts_sizemodel, stockparts_unitprice, stockparts_whitestock, stockparts_blackstock, stockparts_purplestock) VALUES ('mudguard', 1, 20, 20, 140, 80);
INSERT INTO table_stockparts(stockparts_name, stockparts_sizemodel, stockparts_unitprice, stockparts_whitestock, stockparts_blackstock, stockparts_purplestock) VALUES ('mudguard', 2, 22, 120, 140, 80);
INSERT INTO table_stockparts(stockparts_name, stockparts_sizemodel, stockparts_unitprice, stockparts_blackstock) VALUES ('wide mudguard', 1, 25, 120);
INSERT INTO table_stockparts(stockparts_name, stockparts_sizemodel, stockparts_unitprice, stockparts_blackstock) VALUES ('wide mudguard', 2, 27, 140);
INSERT INTO table_stockparts(stockparts_name, stockparts_sizemodel, stockparts_unitprice, stockparts_nocolorstock) VALUES('inner tube', 1, 6, 300);
INSERT INTO table_stockparts(stockparts_name, stockparts_sizemodel, stockparts_unitprice, stockparts_nocolorstock) VALUES('derailleur', 1, 35, 300);
INSERT INTO table_stockparts(stockparts_name, stockparts_sizemodel, stockparts_unitprice, stockparts_nocolorstock) VALUES('brake disk', 1, 25, 300);
INSERT INTO table_stockparts(stockparts_name, stockparts_sizemodel, stockparts_unitprice, stockparts_nocolorstock) VALUES('lighting', 1, 17, 300);
INSERT INTO table_stockparts(stockparts_name, stockparts_sizemodel, stockparts_unitprice, stockparts_nocolorstock) VALUES ('fork', 1, 80, 300);
INSERT INTO table_stockparts(stockparts_name, stockparts_sizemodel, stockparts_unitprice, stockparts_nocolorstock) VALUES ('fork', 2, 100, 300);
INSERT INTO table_stockparts(stockparts_name, stockparts_sizemodel, stockparts_unitprice, stockparts_nocolorstock) VALUES('handlebar', 1, 70, 300);
INSERT INTO table_stockparts(stockparts_name, stockparts_sizemodel, stockparts_unitprice, stockparts_nocolorstock) VALUES('chainring', 1, 120, 300);
INSERT INTO table_stockparts(stockparts_name, stockparts_sizemodel, stockparts_unitprice, stockparts_nocolorstock) VALUES ('tire', 1, 62, 300);
INSERT INTO table_stockparts(stockparts_name, stockparts_sizemodel, stockparts_unitprice, stockparts_nocolorstock) VALUES ('tire', 2, 67, 300);
INSERT INTO table_stockparts(stockparts_name, stockparts_sizemodel, stockparts_unitprice, stockparts_nocolorstock) VALUES ('wide tire', 1, 70, 300);
INSERT INTO table_stockparts(stockparts_name, stockparts_sizemodel, stockparts_unitprice, stockparts_nocolorstock) VALUES ('wide tire', 2, 75, 300);
INSERT INTO table_stockparts(stockparts_name, stockparts_sizemodel, stockparts_unitprice, stockparts_nocolorstock) VALUES('luggage rack', 1, 21,300);
INSERT INTO table_stockparts(stockparts_name, stockparts_sizemodel, stockparts_unitprice, stockparts_nocolorstock) VALUES ('wheel', 1, 34, 300);
INSERT INTO table_stockparts(stockparts_name, stockparts_sizemodel, stockparts_unitprice, stockparts_nocolorstock) VALUES ('wheel', 2, 36, 300);
INSERT INTO table_stockparts(stockparts_name, stockparts_sizemodel, stockparts_unitprice, stockparts_nocolorstock) VALUES('saddle', 1, 13, 300);
SELECT * FROM table_stockparts;